//! Generates the CycloneDX SBOM document for an output and collects SBOM
//! files dropped by the build script into `info/sboms/`.
use std::{
    collections::{BTreeMap, BTreeSet},
    ffi::OsStr,
    path::{Path, PathBuf},
    str::FromStr,
};

use cyclonedx_bom::{
    external_models::{date_time::DateTime, normalized_string::NormalizedString, uri::Purl},
    models::{
        bom::{Bom, SpecVersion, UrnUuid},
        component::{Classification, Component, Components, Scope},
        dependency::{Dependencies, Dependency},
        external_reference::{
            BomLink, ExternalReference, ExternalReferenceType, ExternalReferences,
            Uri as ReferenceUri,
        },
        hash::{Hash, HashAlgorithm, HashValue, Hashes},
        license::{LicenseChoice, Licenses},
        metadata::Metadata,
        property::{Properties, Property},
        tool::Tools,
    },
    prelude::Uri,
};
use fs_err as fs;
use itertools::Itertools;
use rattler_conda_types::RepoDataRecord;
use url::Url;
use uuid::Uuid;

use crate::{metadata::Output, packaging::PackagingError};

/// Name of the SBOM document generated by rattler-build inside `info/sboms/`.
pub const GENERATED_SBOM_FILE_NAME: &str = "rattler-build.cdx.json";

/// A file collected from the build's SBOM directory.
struct CollectedSbom {
    /// File name inside `info/sboms/`.
    file_name: String,
    /// BOM-Link when the file identifies itself as a CycloneDX document.
    bom_link: Option<String>,
}

/// A resolved record together with the environments it appears in.
struct EnvironmentRecord<'a> {
    record: &'a RepoDataRecord,
    /// The record's purl, used as the component's `purl` field. The bom-ref may
    /// differ from this when it would collide with the primary component.
    purl: String,
    /// Environment labels the record appears in, e.g. `host`, `build`,
    /// `cache-host` and `cache-build`. One property is emitted per label.
    environments: BTreeSet<&'static str>,
    /// Whether the record appears in a host-like environment. Required scope
    /// wins over excluded when a record appears in both.
    required: bool,
}

/// Deterministic serial number so identical builds produce identical SBOMs.
fn serial_number(output: &Output) -> UrnUuid {
    let namespace = Uuid::new_v5(&Uuid::NAMESPACE_DNS, b"rattler.build");
    let identifier = format!(
        "{}/{}-{}",
        output.build_configuration.target_platform,
        output.identifier(),
        output.build_configuration.timestamp.as_second()
    );
    UrnUuid::from(Uuid::new_v5(&namespace, identifier.as_bytes()))
}

/// Build a `pkg:conda` purl string. Qualifier values are percent encoded and
/// emitted in the alphabetical key order mandated by the purl spec.
fn conda_purl(
    name: &str,
    version: &str,
    build: &str,
    channel: Option<&str>,
    subdir: &str,
) -> String {
    let mut purl = format!(
        "pkg:conda/{name}@{}?build={}",
        urlencoding::encode(version),
        urlencoding::encode(build)
    );
    if let Some(channel) = channel {
        purl.push_str("&channel=");
        purl.push_str(&urlencoding::encode(channel));
    }
    purl.push_str("&subdir=");
    purl.push_str(&urlencoding::encode(subdir));
    purl
}

/// Derive a channel name from a channel URL: all non-empty path segments,
/// joined with '/', after stripping a trailing subdir segment. This keeps the
/// label path of label channels intact (e.g. `conda-forge/label/rust_dev`).
fn channel_short_name(channel: &str, subdir: &str) -> Option<String> {
    match Url::parse(channel) {
        Ok(url) => {
            let mut segments: Vec<_> = url.path_segments()?.filter(|s| !s.is_empty()).collect();
            if segments.last() == Some(&subdir) {
                segments.pop();
            }
            if segments.is_empty() {
                None
            } else {
                Some(segments.join("/"))
            }
        }
        // channels can also be configured as plain names
        Err(_) if !channel.is_empty() && !channel.contains('/') => Some(channel.to_string()),
        Err(_) => None,
    }
}

/// The purl of a resolved record, the basis for its bom-ref.
fn record_purl(record: &RepoDataRecord) -> String {
    let package = &record.package_record;
    let channel = record
        .channel
        .as_deref()
        .and_then(|channel| channel_short_name(channel, &package.subdir));
    conda_purl(
        package.name.as_normalized(),
        &package.version.to_string(),
        &package.build,
        channel.as_deref(),
        &package.subdir,
    )
}

/// Emit an SPDX expression license when the string parses as one, a named
/// license otherwise.
fn license_choice(license: &str) -> LicenseChoice {
    if spdx::Expression::parse(license).is_ok() {
        LicenseChoice::expression(license)
    } else {
        LicenseChoice::license(license)
    }
}

/// Sort properties by name and value for reproducible output.
fn sorted_properties(mut properties: Vec<Property>) -> Option<Properties> {
    if properties.is_empty() {
        return None;
    }
    properties.sort_by(|a, b| (&a.name, &*a.value).cmp(&(&b.name, &*b.value)));
    Some(Properties(properties))
}

/// Best effort peek into a collected JSON document. Returns a BOM-Link when
/// the top level object carries a `serialNumber` urn:uuid string and a
/// positive integer `version`.
fn peek_bom_link(content: &str) -> Option<String> {
    let value: serde_json::Value = serde_json::from_str(content).ok()?;
    let serial = value.get("serialNumber")?.as_str()?;
    let version = value.get("version")?.as_u64()?;
    if version == 0 {
        return None;
    }
    let uuid = Uuid::parse_str(serial.strip_prefix("urn:uuid:")?).ok()?;
    Some(format!("urn:cdx:{uuid}/{version}"))
}

/// Generate the CycloneDX document describing the output: the package itself,
/// the resolved host, build and staging cache environments, the run dependency
/// specs and references to the collected SBOM files.
fn generate_sbom(output: &Output, collected: &[CollectedSbom]) -> Result<Bom, PackagingError> {
    let finalized = output.finalized_dependencies.as_ref();
    let host = finalized.and_then(|dependencies| dependencies.host.as_ref());
    let build = finalized.and_then(|dependencies| dependencies.build.as_ref());
    let cache = output.finalized_cache_dependencies.as_ref();
    let cache_host = cache.and_then(|dependencies| dependencies.host.as_ref());
    let cache_build = cache.and_then(|dependencies| dependencies.build.as_ref());

    // primary component identity, also used to detect bom-ref collisions
    let name = output.name().as_normalized();
    let version = output.version().to_string();
    let subdir = output.build_configuration.target_platform.to_string();
    let primary_purl = conda_purl(name, &version, &output.build_string(), None, &subdir);

    // a record whose purl equals the primary's purl needs a distinct bom-ref;
    // bom-refs are opaque strings, so a suffix keeps it unique and deterministic
    // without touching the record's own purl
    let bom_ref = |purl: &str| -> String {
        if purl == primary_purl {
            format!("{purl}#resolved")
        } else {
            purl.to_string()
        }
    };

    // one component per unique record across every environment, keyed by bom-ref
    let mut records: BTreeMap<String, EnvironmentRecord> = BTreeMap::new();
    // the records resolved from the direct specs of every environment
    let mut primary_depends = BTreeSet::new();
    // for every record, its `depends` entries resolved by name within the
    // environment(s) it appears in
    let mut record_depends: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();

    // host-like environments contribute the required scope, build-like ones the
    // excluded scope; each contributes its own `environment` property
    let environments = [
        (host, "host", true),
        (build, "build", false),
        (cache_host, "cache-host", true),
        (cache_build, "cache-build", false),
    ];
    for (resolved, environment, required) in environments {
        let Some(resolved) = resolved else { continue };

        let by_name: BTreeMap<&str, String> = resolved
            .resolved
            .iter()
            .map(|record| {
                (
                    record.package_record.name.as_normalized(),
                    bom_ref(&record_purl(record)),
                )
            })
            .collect();

        for spec in &resolved.specs {
            if let Some(reference) = spec
                .spec()
                .name
                .as_exact()
                .and_then(|name| by_name.get(name.as_normalized()))
            {
                primary_depends.insert(reference.clone());
            }
        }

        for record in &resolved.resolved {
            let purl = record_purl(record);
            let reference = bom_ref(&purl);

            let entry = records
                .entry(reference.clone())
                .or_insert_with(|| EnvironmentRecord {
                    record,
                    purl,
                    environments: BTreeSet::new(),
                    required: false,
                });
            entry.environments.insert(environment);
            entry.required |= required;

            let depends = record_depends.entry(reference).or_default();
            for dependency in &record.package_record.depends {
                let name = dependency.split_whitespace().next().unwrap_or(dependency);
                // names that do not resolve within the environment are
                // skipped, e.g. virtual packages
                if let Some(reference) = by_name.get(name) {
                    depends.insert(reference.clone());
                }
            }
        }
    }

    // primary component
    let mut primary = Component::new(
        Classification::Library,
        name,
        &version,
        Some(primary_purl.clone()),
    );
    primary.purl = Some(Purl::from_str(&primary_purl).expect("any string is a valid Purl value"));

    let about = output.recipe.about();
    primary.description = about.summary.as_deref().map(NormalizedString::new);
    if let Some(license) = &about.license {
        primary.licenses = Some(Licenses(vec![license_choice(&license.to_string())]));
    }

    let mut references = Vec::new();
    if let Some(homepage) = &about.homepage {
        references.push(ExternalReference::new(
            ExternalReferenceType::Website,
            Uri::new(homepage.as_str()),
        ));
    }
    if let Some(repository) = &about.repository {
        references.push(ExternalReference::new(
            ExternalReferenceType::Vcs,
            Uri::new(repository.as_str()),
        ));
    }
    for file in collected {
        let url = match &file.bom_link {
            Some(link) => ReferenceUri::BomLink(BomLink(link.clone())),
            None => ReferenceUri::Url(Uri::new(&format!(
                "./{}",
                urlencoding::encode(&file.file_name)
            ))),
        };
        references.push(ExternalReference {
            external_reference_type: ExternalReferenceType::Bom,
            url,
            comment: Some(format!(
                "{} was collected from the SBOM_DIR of the build",
                file.file_name
            )),
            hashes: None,
        });
    }
    if !references.is_empty() {
        primary.external_references = Some(ExternalReferences(references));
    }

    let mut properties = Vec::new();
    if let Some(run) = finalized.map(|dependencies| &dependencies.run) {
        for spec in run
            .depends
            .iter()
            .map(|dep| dep.spec().to_string())
            .unique()
        {
            properties.push(Property::new("rattler-build:depends", &spec));
        }
        for spec in run
            .constraints
            .iter()
            .map(|dep| dep.spec().to_string())
            .unique()
        {
            properties.push(Property::new("rattler-build:constrains", &spec));
        }
    }
    primary.properties = sorted_properties(properties);

    // environment components, sorted by bom-ref
    let mut components = Vec::new();
    for (reference, entry) in &records {
        let package = &entry.record.package_record;
        let mut component = Component::new(
            Classification::Library,
            package.name.as_normalized(),
            &package.version.to_string(),
            Some(reference.clone()),
        );
        component.purl =
            Some(Purl::from_str(&entry.purl).expect("any string is a valid Purl value"));
        component.scope = Some(if entry.required {
            Scope::Required
        } else {
            Scope::Excluded
        });

        let mut hashes = Vec::new();
        if let Some(md5) = &package.md5 {
            hashes.push(Hash {
                alg: HashAlgorithm::MD5,
                content: HashValue(hex::encode(md5)),
            });
        }
        if let Some(sha256) = &package.sha256 {
            hashes.push(Hash {
                alg: HashAlgorithm::SHA_256,
                content: HashValue(hex::encode(sha256)),
            });
        }
        if !hashes.is_empty() {
            component.hashes = Some(Hashes(hashes));
        }

        if let Some(license) = &package.license {
            component.licenses = Some(Licenses(vec![license_choice(license)]));
        }

        component.external_references = Some(ExternalReferences(vec![ExternalReference::new(
            ExternalReferenceType::Distribution,
            Uri::new(entry.record.url.as_str()),
        )]));

        let mut properties = Vec::new();
        for environment in &entry.environments {
            properties.push(Property::new("rattler-build:environment", environment));
        }
        for mapped in package.purls.iter().flatten() {
            properties.push(Property::new(
                "rattler-build:mapped-purl",
                &mapped.to_string(),
            ));
        }
        component.properties = sorted_properties(properties);

        components.push(component);
    }

    let mut dependencies = vec![Dependency {
        dependency_ref: primary_purl,
        dependencies: primary_depends.into_iter().collect(),
    }];
    for reference in records.keys() {
        dependencies.push(Dependency {
            dependency_ref: reference.clone(),
            dependencies: record_depends
                .remove(reference)
                .unwrap_or_default()
                .into_iter()
                .collect(),
        });
    }

    let build_tool = output.system_tools.build_tool();
    let tool = Component::new(
        Classification::Application,
        &build_tool.name,
        &build_tool.version,
        None,
    );

    let timestamp = output.build_configuration.timestamp.to_string();
    let metadata = Metadata {
        timestamp: Some(
            DateTime::try_from(timestamp)
                .map_err(|err| PackagingError::SbomGenerationError(err.to_string()))?,
        ),
        tools: Some(Tools::Object {
            services: None,
            components: Some(Components(vec![tool])),
        }),
        component: Some(primary),
        ..Metadata::default()
    };

    Ok(Bom {
        version: 1,
        serial_number: Some(serial_number(output)),
        metadata: Some(metadata),
        components: Some(Components(components)),
        services: None,
        external_references: None,
        dependencies: Some(Dependencies(dependencies)),
        compositions: None,
        properties: None,
        vulnerabilities: None,
        signature: None,
        annotations: None,
        formulation: None,
        spec_version: SpecVersion::V1_5,
    })
}

/// Serialize the document as pretty printed CycloneDX 1.5 JSON with a
/// trailing newline.
fn render_sbom(bom: Bom) -> Result<Vec<u8>, PackagingError> {
    let mut buffer = Vec::new();
    bom.output_as_json_v1_5(&mut buffer)
        .map_err(|err| PackagingError::SbomGenerationError(err.to_string()))?;
    buffer.push(b'\n');
    Ok(buffer)
}

/// Validate a collected file's name: reject non-UTF-8 names, and names that
/// collide with the reserved generated document. The reserved-name comparison
/// is case-insensitive because a case variant would still overwrite the
/// generated document on case-insensitive filesystems. `path` is the full
/// source path, used for error reporting.
fn collected_file_name(os_file_name: &OsStr, path: &Path) -> Result<String, PackagingError> {
    let file_name = os_file_name
        .to_str()
        .ok_or_else(|| PackagingError::SbomNonUtf8FileName(path.to_path_buf()))?;
    if file_name.eq_ignore_ascii_case(GENERATED_SBOM_FILE_NAME) {
        return Err(PackagingError::SbomReservedFileName(file_name.to_string()));
    }
    Ok(file_name.to_string())
}

/// True when the path has a `json` extension, compared case-insensitively.
fn has_json_extension(path: &Path) -> bool {
    path.extension()
        .and_then(|extension| extension.to_str())
        .is_some_and(|extension| extension.eq_ignore_ascii_case("json"))
}

/// Copy the files from the build's SBOM directory into `info/sboms/` and
/// write the generated CycloneDX document next to them. Returns the paths of
/// all written files.
pub(crate) fn write_sbom_folder(
    output: &Output,
    tmp_dir_path: &Path,
) -> Result<Vec<PathBuf>, PackagingError> {
    let sboms_folder = tmp_dir_path.join("info/sboms");
    fs::create_dir_all(&sboms_folder)?;

    let sbom_dir = output.build_configuration.directories.sbom_dir();
    let mut sources = Vec::new();
    if sbom_dir.is_dir() {
        for entry in fs::read_dir(&sbom_dir)? {
            let path = entry?.path();
            // only regular files are collected, no directories and no
            // recursion
            if path.is_file() {
                sources.push(path);
            }
        }
    }
    sources.sort_by_key(|path| path.file_name().map(|name| name.to_os_string()));

    let mut files = Vec::new();
    let mut collected = Vec::new();
    for path in sources {
        let os_file_name = path.file_name().expect("read_dir entries have a file name");
        let file_name = collected_file_name(os_file_name, &path)?;

        let destination = sboms_folder.join(os_file_name);
        fs::copy(&path, &destination)?;
        files.push(destination);

        let bom_link = has_json_extension(&path)
            .then(|| fs::read_to_string(&path).ok())
            .flatten()
            .and_then(|content| peek_bom_link(&content));
        collected.push(CollectedSbom {
            file_name,
            bom_link,
        });
    }

    let bom = generate_sbom(output, &collected)?;
    let generated = sboms_folder.join(GENERATED_SBOM_FILE_NAME);
    fs::write(&generated, render_sbom(bom)?)?;
    files.push(generated);

    Ok(files)
}

#[cfg(test)]
mod tests {
    use cyclonedx_bom::validation::Validate;
    use insta::assert_snapshot;

    use rattler_conda_types::{MatchSpec, PackageUrl, ParseStrictness};

    use super::*;
    use crate::render::resolved_dependencies::{
        DependencyInfo, FinalizedDependencies, FinalizedRunDependencies, ResolvedDependencies,
        SourceDependency,
    };

    fn curl_output() -> Output {
        let path = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../test-data/rendered_recipes/curl_recipe.yaml");
        serde_yaml::from_str(&fs::read_to_string(path).unwrap()).unwrap()
    }

    fn source_spec(spec: &str) -> DependencyInfo {
        SourceDependency {
            spec: MatchSpec::from_str(spec, ParseStrictness::Lenient).unwrap(),
        }
        .into()
    }

    /// All `(name, value)` property pairs of a component.
    fn property_values(component: &Component) -> Vec<(String, String)> {
        component
            .properties
            .as_ref()
            .map(|properties| {
                properties
                    .0
                    .iter()
                    .map(|property| (property.name.to_string(), property.value.to_string()))
                    .collect()
            })
            .unwrap_or_default()
    }

    fn collected_files() -> Vec<CollectedSbom> {
        vec![
            CollectedSbom {
                file_name: "syft.spdx.json".to_string(),
                bom_link: None,
            },
            CollectedSbom {
                file_name: "vendored.cdx.json".to_string(),
                bom_link: Some("urn:cdx:3e671687-395b-41f5-a30f-a58921a69b79/1".to_string()),
            },
        ]
    }

    #[test]
    fn test_sbom_conda_purl() {
        assert_eq!(
            conda_purl("curl", "8.0.1", "h60d57d3_0", None, "osx-arm64"),
            "pkg:conda/curl@8.0.1?build=h60d57d3_0&subdir=osx-arm64"
        );
        assert_eq!(
            conda_purl("libfoo", "1!2.0+3", "0_h1", Some("conda-forge"), "linux-64"),
            "pkg:conda/libfoo@1%212.0%2B3?build=0_h1&channel=conda-forge&subdir=linux-64"
        );
    }

    #[test]
    fn test_sbom_channel_short_name() {
        assert_eq!(
            channel_short_name("https://conda.anaconda.org/conda-forge/", "linux-64").as_deref(),
            Some("conda-forge")
        );
        assert_eq!(
            channel_short_name("https://prefix.dev/conda-forge", "linux-64").as_deref(),
            Some("conda-forge")
        );
        assert_eq!(
            channel_short_name(
                "https://conda.anaconda.org/conda-forge/linux-64",
                "linux-64"
            )
            .as_deref(),
            Some("conda-forge")
        );
        assert_eq!(
            channel_short_name("https://repo.prefix.dev/my-channel/osx-arm64/", "osx-arm64")
                .as_deref(),
            Some("my-channel")
        );
        // label channels keep their full label path
        assert_eq!(
            channel_short_name(
                "https://conda.anaconda.org/conda-forge/label/rust_dev",
                "linux-64"
            )
            .as_deref(),
            Some("conda-forge/label/rust_dev")
        );
        assert_eq!(
            channel_short_name(
                "https://conda.anaconda.org/conda-forge/label/rust_dev/linux-64",
                "linux-64"
            )
            .as_deref(),
            Some("conda-forge/label/rust_dev")
        );
        assert_eq!(
            channel_short_name("https://conda.anaconda.org/", "linux-64"),
            None
        );
        assert_eq!(
            channel_short_name("conda-forge", "linux-64").as_deref(),
            Some("conda-forge")
        );
        assert_eq!(channel_short_name("", "linux-64"), None);
    }

    #[test]
    fn test_sbom_license_expression_or_name() {
        assert!(matches!(
            license_choice("Apache-2.0 WITH LLVM-exception"),
            LicenseChoice::Expression(_)
        ));
        assert!(matches!(
            license_choice("GPL-1.0-or-later OR Artistic-1.0-Perl"),
            LicenseChoice::Expression(_)
        ));
        assert!(matches!(
            license_choice("GPL and LGPL"),
            LicenseChoice::License(_)
        ));
        assert!(matches!(
            license_choice("Proprietary license"),
            LicenseChoice::License(_)
        ));
    }

    #[test]
    fn test_sbom_peek_bom_link() {
        assert_eq!(
            peek_bom_link(
                r#"{"serialNumber": "urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79", "version": 7}"#
            )
            .as_deref(),
            Some("urn:cdx:3e671687-395b-41f5-a30f-a58921a69b79/7")
        );
        // not a urn:uuid serial number
        assert_eq!(
            peek_bom_link(r#"{"serialNumber": "not-a-urn", "version": 1}"#),
            None
        );
        // version has to be a positive integer
        assert_eq!(
            peek_bom_link(
                r#"{"serialNumber": "urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79", "version": "7"}"#
            ),
            None
        );
        assert_eq!(
            peek_bom_link(
                r#"{"serialNumber": "urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79", "version": 0}"#
            ),
            None
        );
        assert_eq!(peek_bom_link(r#"{"version": 1}"#), None);
        assert_eq!(peek_bom_link("not json"), None);
    }

    #[test]
    fn test_sbom_host_build_dedup_and_scope() {
        let mut output = curl_output();
        let finalized = output.finalized_dependencies.as_mut().unwrap();
        let build = finalized.build.as_ref().unwrap();
        let build_len = build.resolved.len();
        // move two build records into the host environment as well
        let shared: Vec<_> = build.resolved.iter().take(2).cloned().collect();
        let shared_names: Vec<String> = shared
            .iter()
            .map(|record| record.package_record.name.as_normalized().to_string())
            .collect();
        finalized.host = Some(ResolvedDependencies {
            specs: vec![],
            resolved: shared,
        });

        let bom = generate_sbom(&output, &[]).unwrap();
        let components = bom.components.unwrap().0;
        // records present in both environments are emitted once
        assert_eq!(components.len(), build_len);

        for component in &components {
            let in_host = shared_names.contains(&component.name.to_string());
            let expected_scope = if in_host {
                Scope::Required
            } else {
                Scope::Excluded
            };
            assert_eq!(component.scope.as_ref(), Some(&expected_scope));

            let environments: Vec<String> = component
                .properties
                .as_ref()
                .unwrap()
                .0
                .iter()
                .filter(|property| property.name == "rattler-build:environment")
                .map(|property| property.value.to_string())
                .collect();
            if in_host {
                assert_eq!(environments, ["build", "host"]);
            } else {
                assert_eq!(environments, ["build"]);
            }
        }
    }

    #[test]
    fn test_sbom_document_validates() {
        let bom = generate_sbom(&curl_output(), &collected_files()).unwrap();
        let result = bom.validate_version(SpecVersion::V1_5);
        assert!(result.passed(), "{result:?}");
    }

    #[test]
    fn test_sbom_curl_snapshot() {
        let bom = generate_sbom(&curl_output(), &collected_files()).unwrap();
        let json = String::from_utf8(render_sbom(bom).unwrap()).unwrap();
        assert_snapshot!(json);
    }

    #[test]
    fn test_sbom_reserved_file_name_is_case_insensitive() {
        // a case variant would still overwrite the generated document on
        // case-insensitive filesystems, so it is rejected too
        let path = Path::new("sbom").join("RATTLER-BUILD.CDX.JSON");
        let err = collected_file_name(path.file_name().unwrap(), &path).unwrap_err();
        assert!(matches!(err, PackagingError::SbomReservedFileName(_)));

        let other = Path::new("sbom").join("vendored.cdx.json");
        assert_eq!(
            collected_file_name(other.file_name().unwrap(), &other).unwrap(),
            "vendored.cdx.json"
        );
    }

    #[cfg(unix)]
    #[test]
    fn test_sbom_non_utf8_file_name_is_rejected() {
        use std::os::unix::ffi::OsStrExt;
        let os_name = OsStr::from_bytes(b"bad\xffname.json");
        let path = Path::new("sbom").join(os_name);
        let err = collected_file_name(os_name, &path).unwrap_err();
        assert!(matches!(err, PackagingError::SbomNonUtf8FileName(_)));
    }

    #[test]
    fn test_sbom_json_extension_is_case_insensitive() {
        assert!(has_json_extension(Path::new("vendored.cdx.JSON")));
        assert!(has_json_extension(Path::new("a.json")));
        assert!(!has_json_extension(Path::new("a.txt")));
        assert!(!has_json_extension(Path::new("noextension")));
    }

    #[test]
    fn test_sbom_relative_reference_is_percent_encoded() {
        let collected = vec![CollectedSbom {
            file_name: "third party #1.json".to_string(),
            bom_link: None,
        }];
        let bom = generate_sbom(&curl_output(), &collected).unwrap();
        let json = String::from_utf8(render_sbom(bom).unwrap()).unwrap();
        assert!(json.contains("./third%20party%20%231.json"), "{json}");
    }

    #[test]
    fn test_sbom_bom_ref_collision_disambiguated() {
        let mut output = curl_output();
        let subdir = output.build_configuration.target_platform.to_string();
        let name = output.name().clone();
        let version = output.version().clone();
        let build = output.build_string().into_owned();
        let primary_purl = conda_purl(
            name.as_normalized(),
            &version.to_string(),
            &build,
            None,
            &subdir,
        );

        // a resolved host record identical to the primary with no derivable
        // channel produces the same purl and would collide with the primary
        let finalized = output.finalized_dependencies.as_mut().unwrap();
        let mut record = finalized.build.as_ref().unwrap().resolved[0].clone();
        record.channel = None;
        record.package_record.name = name;
        record.package_record.version = version;
        record.package_record.build = build;
        record.package_record.subdir = subdir;
        finalized.host = Some(ResolvedDependencies {
            specs: vec![],
            resolved: vec![record],
        });

        let bom = generate_sbom(&output, &[]).unwrap();

        // the colliding record keeps its purl but gets a distinct bom-ref
        let resolved_ref = format!("{primary_purl}#resolved");
        let component = bom
            .components
            .as_ref()
            .unwrap()
            .0
            .iter()
            .find(|component| component.bom_ref.as_deref() == Some(resolved_ref.as_str()))
            .expect("colliding record gets a disambiguated bom-ref");
        assert_eq!(
            component.purl.as_ref().map(|purl| purl.to_string()),
            Some(primary_purl.clone())
        );

        // the primary keeps the plain purl as its bom-ref, so both are unique
        let primary = bom.metadata.unwrap().component.unwrap();
        assert_eq!(primary.bom_ref.as_deref(), Some(primary_purl.as_str()));

        // the dependency graph references both the primary and the resolved ref
        let refs: Vec<String> = bom
            .dependencies
            .unwrap()
            .0
            .iter()
            .map(|dependency| dependency.dependency_ref.clone())
            .collect();
        assert!(refs.contains(&resolved_ref));
        assert!(refs.contains(&primary_purl));
    }

    #[test]
    fn test_sbom_includes_cache_environments() {
        let mut output = curl_output();
        let template = output
            .finalized_dependencies
            .as_ref()
            .unwrap()
            .build
            .as_ref()
            .unwrap()
            .resolved[0]
            .clone();

        let mut cache_host = template.clone();
        cache_host.package_record.name = "cachehostpkg".parse().unwrap();
        let mut cache_build = template;
        cache_build.package_record.name = "cachebuildpkg".parse().unwrap();

        output.finalized_cache_dependencies = Some(FinalizedDependencies {
            build: Some(ResolvedDependencies {
                specs: vec![],
                resolved: vec![cache_build],
            }),
            host: Some(ResolvedDependencies {
                specs: vec![],
                resolved: vec![cache_host],
            }),
            run: FinalizedRunDependencies {
                depends: vec![],
                constraints: vec![],
                extra_depends: Default::default(),
                run_exports: Default::default(),
            },
        });

        let bom = generate_sbom(&output, &[]).unwrap();
        let components = bom.components.unwrap().0;
        let find = |name: &str| {
            components
                .iter()
                .find(|component| component.name.to_string() == name)
                .unwrap_or_else(|| panic!("component {name} is present"))
        };

        let host = find("cachehostpkg");
        assert_eq!(host.scope, Some(Scope::Required));
        assert!(property_values(host).contains(&(
            "rattler-build:environment".to_string(),
            "cache-host".to_string()
        )));

        let build = find("cachebuildpkg");
        assert_eq!(build.scope, Some(Scope::Excluded));
        assert!(property_values(build).contains(&(
            "rattler-build:environment".to_string(),
            "cache-build".to_string()
        )));
    }

    #[test]
    fn test_sbom_dependency_and_mapped_purl_properties() {
        let mut output = curl_output();

        let depends = source_spec("foo >=1.0");
        let constrains = source_spec("bar <2.0");
        let expected_depends = depends.spec().to_string();
        let expected_constrains = constrains.spec().to_string();

        let finalized = output.finalized_dependencies.as_mut().unwrap();
        finalized.run.depends = vec![depends];
        finalized.run.constraints = vec![constrains];

        // attach a mapped purl to the first build record
        let mapped: PackageUrl = "pkg:pypi/foo@1.2.3".parse().unwrap();
        let record = &mut finalized.build.as_mut().unwrap().resolved[0];
        record.package_record.purls = Some(BTreeSet::from([mapped]));
        let mapped_record = record.package_record.name.as_normalized().to_string();

        let bom = generate_sbom(&output, &[]).unwrap();

        let primary = bom.metadata.as_ref().unwrap().component.as_ref().unwrap();
        let primary_properties = property_values(primary);
        assert!(
            primary_properties.contains(&("rattler-build:depends".to_string(), expected_depends))
        );
        assert!(
            primary_properties
                .contains(&("rattler-build:constrains".to_string(), expected_constrains))
        );

        let component = bom
            .components
            .as_ref()
            .unwrap()
            .0
            .iter()
            .find(|component| component.name.to_string() == mapped_record)
            .expect("mapped record is present");
        assert!(property_values(component).contains(&(
            "rattler-build:mapped-purl".to_string(),
            "pkg:pypi/foo@1.2.3".to_string()
        )));
    }
}
